spring:
  application:
    name: io

  datasource:
    url: jdbc:mysql://localhost:3306/db_restaurante
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: ${JWT_SECRET}
  expiration: 36000000

logging:
  level:
    com.restauranteHelper.io: WARN
